- id: prettier
  name: prettier
  description: 'Prettier is an opinionated code formatter.'
  entry: prettier --write --list-different
  language: node
  files: (?i)\.(json|js|jsx|ts|tsx)$

- id: eslint
  name: eslint
  description: 'Find and fix problems in your JavaScript code.'
  entry: eslint
  language: node
  files: (?i)\.(js|jsx|ts|tsx)$

- id: black
  name: black
  description: 'Black: The uncompromising Python code formatter'
  entry: black
  language: python
  language_version: python3
  require_serial: true
  types: [python]

- id: flake8
  name: flake8
  description: '`flake8` is a command-line utility for enforcing style consistency across Python projects.'
  entry: flake8
  language: python
  types: [python]
  require_serial: true

- id: isort
  name: isort
  description: 'A Python utility / library to sort imports.'
  entry: isort
  language: python
  types: [python]

- id: black-nb
  name: black-nb
  description: 'Black: The uncompromising Python code formatter for Jupyter notebooks'
  entry: black-nb
  args: ['-l', '88']
  language: python
  language_version: python3
  require_serial: true
  files: (?i)\.ipynb$

- id: flake8-nb
  name: flake8-nb
  description: '`flake8_nb` is a command-line utility for enforcing style consistency across jupyter notebooks.'
  entry: flake8_nb
  language: python
  files: (?i)\.ipynb$
  require_serial: true

- id: gofmt
  name: gofmt
  description: 'Automatically formats Go source code. Go needs to be installed'
  entry: gofmt -l -w
  language: golang
  types: [go]
